### ISSUE TITLE
HIstorical data compatibility

### ISSUE THREAD

**Issue by artiko88** [JJJerome/rl4mm#2]
Hey!

Fantastic project, i must say. Surprised by the lack of discussions even as raised issues, given the scope and features of the project.

I was wondering, if it is possible to somehow integrate data from Tardis (cryptocurrency historical data provider) into this framework and run simulations?

**Comment by JJJerome** [comment]
Hi @artiko88,
Thanks a lot for your interest in rl4mm! Unfortunately, the repository is optimised for Nasdaq orderflow (ITCH) data. Tardis only deals in trade-and-quote (TAQ) data, so whilst it would be possible to modify rl4mm to use TAQ, there might be faster ways to run a simulator by making certain assumptions (since you need to make assumptions about order cancellations, etc, with TAQ anyway). If you are working with Tardis data and decide to extend compatibility to their datasets, please open a PR though, I am sure there are other users that would like this functionality!
All the best
